version: '3.8'
services:
  menteenpaz-service:
    container_name: menteenpaz-service
    image: postgres:16.2-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: menteenpaz-db
    restart: always