spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/menteenpaz-db
    username: admin
    password: 123456789

    flyway:
      enabled: true
      baselineOnMigrate: true
      validateOnMigrate: true
      locations: classpath:db/migration
      user: admin
      password: 123456789
