CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE CONSULTANTS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NAME CHARACTER VARYING NOT NULL,
    LAST_NAME CHARACTER VARYING NOT NULL,
    BIRTHDAY DATE NOT NULL,
    SEX CHARACTER NOT NULL
);