INSERT INTO CONSULTANTS (NAME, LAST_NAME, BIRTHDAY, SEX)
VALUES ('VANESSA', 'PORRAS', '1993-10-28', 'F');

INSERT INTO CONSULTANTS (NAME, LAST_NAME, BIRTHDAY, SEX)
VALUES ('FRANK', 'DAZA', '1989-09-13', 'M');